# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 380d0fb6d7b690f8ada6a535fdc69b8e5c6121825ca58bbe141deca693fb3664dee6bb660b01418c8c132af7b9de1b5e7c07667d308c25d73c9879952547ece7

test:
  secret_key_base: ac0f610ffc4d31503f261543fb9203a34c62a72e9da1efed03e97398569c37cfe3ae8ea898089b5d5378e96224d11b1fe2fcfab961d6e76ea7e74f4fb7c16c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
